let x = 16.75;
let rounded = Math.round(x);
let sqrt = Math.sqrt(x);
let power = Math.pow(x, 3);
let randomNum = Math.floor(Math.random() * 41) + 10;
console.log(`Number: ${x}`);
console.log(`Rounded: ${rounded}`);
console.log(`Square root: ${sqrt}`);
console.log(`Power of 3: ${power}`);
console.log(`Random (10-50): ${randomNum}`);
